// define the items; we could add fields like tags, type, etc.
// if Latex code is used, slashes need to be escaped, eg. $x^2 + \\frac{1}{2+x}$
var items = [];
items.push({
 'name': 'The Buildings Gallery',
 'creator': 'Bram Bekker, Maarten Solleveld',
 'link': 'https://buildings.gallery',
 'description': 'Visualisation tool for some spherical and affine buildings.',
 'image': '',
 'video': '',
 'reference': 'https://arxiv.org/abs/2011.11707',
 'source': '',
 'tags': 'webpage,paper,tool',
});
///
items.push({
 'name': 'Focus-model drawing tool for regular trees',
 'creator': 'David Allingham',
 'link': 'https://dalling1.github.io/focusmodels/',
 'description': 'Tools for drawing regular trees in layouts focusing on a vertex, edge, axis or ray.',
 'image': '',
 'video': '',
 'reference': '',
 'source': 'https://github.com/dalling1/focusmodels',
 'tags': 'webpage,tool,source',
});
///
items.push({
 'name': 'Visualiser of the action $\\mathrm{PGL}(2,\\mathbb{Q}_{p})$ $\\curvearrowright T_{p+1}$.',
 'creator': 'Ari Markowitz',
 'link': 'https://ariymarkowitz.github.io/Bruhat-Tits-Tree-Visualiser/',
 'description': 'A visualiser for the action of $\\mathrm{PGL}(2,\\mathbb{Q}_{p})$ on its Bruhat-Tits tree.',
 'image': '',
 'video': '',
 'reference': '',
 'source': '',
 'tags': 'webpage,tool',
});
///
items.push({
 'name': 'Drawing tool for free product graphs',
 'creator': 'David Allingham',
 'link': 'https://dalling1.github.io/freeproductgraphs/',
 'description': 'A tool for drawing the free product of user-specified graphs.',
 'image': '',
 'video': '',
 'reference': 'https://arxiv.org/abs/2002.10639',
 'source': 'https://github.com/dalling1/freeproductgraphs',
 'tags': 'webpage,tool,source,paper',
});
///
items.push({
 'name': 'Drawing tool for label-regular trees',
 'creator': 'David Allingham',
 'link': 'https://dalling1.github.io/labelregulartrees/',
 'description': 'A tool for drawing a label-regular tree from a user-specified generating matrix.',
 'image': '',
 'video': '',
 'reference': '',
 'source': 'https://github.com/dalling1/labelregulartrees',
 'tags': 'webpage,tool,source',
});
///
items.push({
 'name': 'GAP package for universal groups',
 'creator': '<a href="https://www.newcastle.edu.au/profile/khalil-hannouch">Khalil Hannoch</a>, <a href="https://www.newcastle.edu.au/profile/stephan-tornier">Stephan Tornier</a>',
 'link': 'https://gap-packages.github.io/UGALY/',
 'description': 'UGALY is a GAP package that provides methods to create, analyse and find local actions of generalised universal groups acting on locally finite regular trees, following Burger-Mozes and Tornier.',
 'image': '',
 'video': 'https://www.youtube.com/watch?v=MsoE450ZZtg',
 'reference': 'http://www.numdam.org/item/PMIHES_2000__92__113_0/, https://arxiv.org/abs/2002.09876',
 'source': 'https://github.com/gap-packages/UGALY',
 'tags': 'tool,paper,video,source',
});
///
items.push({
 'name': 'GAP package for self-replicating groups',
 'creator': 'Samuel King, Sarah Shotter, <a href="https://www.newcastle.edu.au/profile/stephan-tornier">Stephan Tornier</a>',
 'link': 'https://github.com/SamSGKing/SRGroups',
 'description': 'SRGroups is a GAP package (under development) for self-replicating groups acting on regular rooted trees.',
 'image': '',
 'video': 'https://www.youtube.com/watch?v=eN3IiQui2ew',
 'reference': 'https://nova.newcastle.edu.au/vital/access/manager/Repository/uon:17152',
 'source': 'https://github.com/SamSGKing/SRGroups',
 'tags': 'tool,paper,source,video',
});
///
items.push({
 'name': 'GAP package for functionally recursive groups',
 'creator': '<a href="http://www.uni-math.gwdg.de/laurent/">Laurent Bartholdi</a>',
 'link': 'https://gap-packages.github.io/fr/',
 'description': 'FR is a GAP package which implements in GAP the basic objects of Mealy machines and functional recursions; and handles groups that they generate, such as self-similar groups.',
 'image': '',
 'video': '',
 'reference': 'https://mathscinet.ams.org/mathscinet-getitem?mr=MR2091700, https://mathscinet.ams.org/mathscinet-getitem?mr=MR2035113',
 'source': 'https://github.com/gap-packages/fr',
 'tags': 'tool,paper,source',
});
///
items.push({
 'name': 'GAP package for finite automata groups',
 'creator': 'Yevgen Muntyan, Dmytro Savchuk',
 'link': 'https://gap-packages.github.io/automgrp/',
 'description': 'AutomGrp is a GAP package which provides methods for computations with groups and semigroups generated by finite automata or given by wreath recursion, as well as with their finitely generated subgroups and elements.',
 'image': '',
 'video': '',
 'reference': 'http://www.mathnet.ru/php/archive.phtml?wshow=paper&jrnid=tm&paperid=515&option_lang=eng',
 'source': 'https://github.com/gap-packages/automgrp',
 'tags': 'tool,paper,source',
});
///
items.push({
 'name': 'Automorphism constructor and explorer',
 'creator': 'David Allingham',
 'link': 'https://dalling1.github.io/automorphisms/',
 'description': 'A tool for constructing automorphisms on trees. Construction can be performed using a graphical interface or by entering the automorphism into a text editor. Labelling and export options are provided.',
 'image': '',
 'video': '',
 'reference': '',
 'source': 'https://github.com/dalling1/automorphisms',
 'tags': 'source,tool,webpage',
});
///
